### ISSUE TITLE
Handle initialization logic for the escrow 

### ISSUE THREAD

**Issue by James-Sangalli** [debtdao/smart-contracts#14]

**Comment by kibagateaux** [comment]
I haven't quite figured this out yet. There's a circular dependency between Loan and modules in that they both reference each other for use in their logic. Right now `Loan.sol` is taking module addresses in its constructor so modules must be deployed first. So i think "initialized" phase is once the module becomes attached to the actual Loan contract when we know loan and modules are pointing to each other.

For the escrow contract, additional logic like depositing collateral could be handled inside the initialization logic or a separate function that the borrower calls when their ready after initialization. I'd like to keep the `init()` interface simple so no arguments passed in and any logic that is required is hardcoded into the modules init function, probably from constructor params that are already stored when we call `init()`

Very open to suggestions on this. Its an important detail and could cause security risks if not done properly

**Comment by James-Sangalli** [comment]
> I haven't quite figured this out yet. There's a circular dependency between Loan and modules in that they both reference each other for use in their logic. Right now `Loan.sol` is taking module addresses in its constructor so modules must be deployed first. So i think "initialized" phase is once the module becomes attached to the actual Loan contract when we know loan and modules are pointing to each other.
> 
> For the escrow contract, additional logic like depositing collateral could be handled inside the initialization logic or a separate function that the borrower calls when their ready after initialization. I'd like to keep the `init()` interface simple so no arguments passed in and any logic that is required is hardcoded into the modules init function, probably from constructor params that are already stored when we call `init()`
> 
> Very open to suggestions on this. Its an important detail and could cause security risks if not done properly

I think it's important that the borrower gets their opportunity to deposit all the tokens that they want to and then assert that they are "ready". We could restrict the loan until this phase is hit and if the borrower is the one who decides when they are ready, it prevents a third party from triggering a malicious default before they had an opportunity to make all the deposits that they wish to.

Keen to talk about this more at the next meeting.

**Comment by kibagateaux** [comment]
What do you mean by "malicious default"? Right now there is a difference between a lender depositing into the Loan contract making funds available to the borrower, and the borrower actually taking out the loan. Once the borrower does actually borrow, I plan on adding a check in the Loan contract that calls your escrow to get collateral ratio and make sure they aren't undercollateralized before sending borrower funds. So it should be impossible for anything to happen before borrower deposits collateral anyway.

Its a bit of a UX question. We've been operating on the assumption that all the terms of the loan will be negotiated offchain and the final terms are codified in these contracts so the borrower should be "ready" before the contracts are even deployed. Thats the only reason it would be possible to define additional logic (e.g. deposit $X of Y token) in `init()` without needing extra parameters because its part of terms of the loan (a.k.a constructor params) already

**Comment by James-Sangalli** [comment]
> What do you mean by "malicious default"? Right now there is a difference between a lender depositing into the Loan contract making funds available to the borrower, and the borrower actually taking out the loan. Once the borrower does actually borrow, I plan on adding a check in the Loan contract that calls your escrow to get collateral ratio and make sure they aren't undercollateralized before sending borrower funds. So it should be impossible for anything to happen before borrower deposits collateral anyway.
> 
> Its a bit of a UX question. We've been operating on the assumption that all the terms of the loan will be negotiated offchain and the final terms are codified in these contracts so the borrower should be "ready" before the contracts are even deployed. Thats the only reason it would be possible to define additional logic (e.g. deposit $X of Y token) in `init()` without needing extra parameters because its part of terms of the loan (a.k.a constructor params) already

What I meant was that the lender could trigger a default before the borrower had a proper opportunity to put up collateral. However, this will not be an issue if we prevent the loan being released until after the borrower has initialised the escrow. 

I suppose the assumption that we can predetermine the initial deposit requirements in advance could hold, the only potential issue could be that the price of such assets could have moved dramatically between the time of agreement and the time of initialisation, such to the point that the cratio falls below the threshold. 

Let's imagine that the lender and borrower agree on the deposit requirements off chain and at the time of the agreement, the cratio would be acceptable in relation to the loan but that is no longer the case by the time of deployment. In that instance, the `init` function would be called, fixed deposits would go in and the loan would be immediately eligible for liquidation. 

Another idea could be this:
1. Escrow is deployed without a predetermined initial deposit
2. Borrower deposits assets via the `addCollateral` function (presumably with a ballpark figure in mind but really they just need an acceptable cratio)
3. Borrower calls the init function when they are done, the init function reverts if the cratio is unacceptable
4. Funds within the loan contract are released post init

What do you think?

**Comment by kibagateaux** [comment]
yea thats definitely a possible options. One other attack vector is that if the Loan contract isn't passed in as constructor arg for Escrow and set in `init` then inbetween step 2 and 3 an attacker could call `init` and set the collateral for a different contract than the intended loan and call `releaseCollateral` stealing funds that way too

**Comment by James-Sangalli** [comment]
@kibagateaux I have had a go at what I think the init logic could look like: https://github.com/debtdao/smart-contracts/blob/f703559370de124c0e673942802c3bd477655e2c/contracts/Escrow.sol#L39

Do you see any issue with the borrower calling this function? This allows them the time to add the collateral and then call the init function when they are ready. The loan contract can then check if the escrow is initialized and then give out the funds.

**Comment by James-Sangalli** [comment]
> @kibagateaux I have had a go at what I think the init logic could look like:
> 
> https://github.com/debtdao/smart-contracts/blob/f703559370de124c0e673942802c3bd477655e2c/contracts/Escrow.sol#L39
> 
> Do you see any issue with the borrower calling this function? This allows them the time to add the collateral and then call the init function when they are ready. The loan contract can then check if the escrow is initialized and then give out the funds.

I see that you have set the escrow contract address in the loan contract. This would assume that the loan contract calls the init function. 

Perhaps we can allow the borrower to set the Loan contract in another function and then have the loan contract call init.

I see this as important because if the init function blindly accepts the loan contract as msg.sender, anyone could set themselves as the loan contract AFTER the borrower has posted up collateral... 

I know we discussed this briefly in the meeting but it would be good to hash it out with more clarity.

**Comment by kibagateaux** [comment]
Definitely agree on the security issues. There are ways to reduce the risk e.g. only allowing deposits if status is already initialized. This prevents hijacking the module and rugpulling borrower unknowingly, if someone does hijack it then its kinda the borrowers fault for not checking they are depositing to the right contract but thats definitely a bad argument.

If we are changing how IDs work in the Loan contract like i mentioned in the call then the Interest Rate can be a singleton too so Escrow will be the only module that needs to directly reference a single Loan contract creating a circular dependency. This definitely reduces the need for the `init` function across all the contracts so we can change the current interface to accommodate our immediate needs since its just an MVP. Do you think it makes sense to change it to `function init(address loan)` and to set Loan and initialize all at once?

**Comment by James-Sangalli** [comment]
> Definitely agree on the security issues. There are ways to reduce the risk e.g. only allowing deposits if status is already initialized. This prevents hijacking the module and rugpulling borrower unknowingly, if someone does hijack it then its kinda the borrowers fault for not checking they are depositing to the right contract but thats definitely a bad argument.
> 
> If we are changing how IDs work in the Loan contract like i mentioned in the call then the Interest Rate can be a singleton too so Escrow will be the only module that needs to directly reference a single Loan contract creating a circular dependency. This definitely reduces the need for the `init` function across all the contracts so we can change the current interface to accommodate our immediate needs since its just an MVP. Do you think it makes sense to change it to `function init(address loan)` and to set Loan and initialize all at once?

Right but if we set the Escrow to initialised before the borrower has an opportunity to deposit, the contract could be liquidated in the interim...

Another option would be to add in a function `setLoanContract(address loan)` and only allow the borrower to call it once they have deposited collateral. That way the loan contract could call `init()` and we wouldn't have to break the `Module` interface. 

Another option on top of that is to use the `active` status for which the borrower would set the contract to `active` post initialisation and after depositing. 

Either case is an easy solution but will require a bit more work for the borrower.

With your idea of using `init(address loan)` I assume that you mean the borrower would be the one to call this?

**Comment by kibagateaux** [comment]
The Loan wouldn't allow them to borrow if they haven't already deposited so it's not an issue. It's like if you approved an asset to be used as collateral before you deposit anything on Aave or Compound, you couldn't be immediately liquidated because the protocol wouldn't allow a loan to be used in the first place with no collateral.

Might be some confusion on terms here. Right now in the Loan contract "initialized" means terms have been defined (borrower, modules, etc.) so[ it becomes initialized in the constructor](https://github.com/debtdao/smart-contracts/blob/f0f7fda42b44042acfa91c794b2989c8a0db834f/contracts/Loan.sol#L69) when all of that is set. It isn't "active" until [`init` is called on the Loan](https://github.com/debtdao/smart-contracts/blob/f0f7fda42b44042acfa91c794b2989c8a0db834f/contracts/Loan.sol#L139) and all other loans return ACTIVE status as well. I think the same should apply to modules, "initialized" means the contract params are set but "active" means loans can actually be issued. These meanings are arbitrarily defined by me so we can change but i think it makes sense and lines up with what you said here 
> Another option on top of that is to use the active status for which the borrower would set the contract to active post initialisation and after depositing.

Maybe we call it `activeLoan(address loan, address[] collateral, uint amount[])` and let borrower set ACTIVE status + deposit  all at once to simplify UX? cc @debtdao/financial_products 

~So maybe Escrow is ACTIVE when collateral value > 0, at that point it's impossible to go back to INITIALIZED and Loan's `init` would pass.~

**Comment by James-Sangalli** [comment]
> The Loan wouldn't allow them to borrow if they haven't already deposited so it's not an issue. It's like if you approved an asset to be used as collateral before you deposit anything on Aave or Compound, you couldn't be immediately liquidated because the protocol wouldn't allow a loan to be used in the first place with no collateral.
> 
> Might be some confusion on terms here. Right now in the Loan contract "initialized" means terms have been defined (borrower, modules, etc.) so[ it becomes initialized in the constructor](https://github.com/debtdao/smart-contracts/blob/f0f7fda42b44042acfa91c794b2989c8a0db834f/contracts/Loan.sol#L69) when all of that is set. It isn't "active" until [`init` is called on the Loan](https://github.com/debtdao/smart-contracts/blob/f0f7fda42b44042acfa91c794b2989c8a0db834f/contracts/Loan.sol#L139) and all other loans return ACTIVE status as well. I think the same should apply to modules, "initialized" means the contract params are set but "active" means loans can actually be issued. These meanings are arbitrarily defined by me so we can change but i think it makes sense and lines up with what you said here
> 
> > Another option on top of that is to use the active status for which the borrower would set the contract to active post initialisation and after depositing.
> 
> Maybe we call it `activeLoan(address loan, address[] collateral, uint amount[])` and let borrower set ACTIVE status + deposit all at once to simplify UX? cc @debtdao/financial_products
> 
> ~So maybe Escrow is ACTIVE when collateral value > 0, at that point it's impossible to go back to INITIALIZED and Loan's `init` would pass.~

Makes sense. Can do something like that.
