### ISSUE TITLE
Build Oracle module

### ISSUE THREAD

**Issue by kibagateaux** [debtdao/smart-contracts#17]
- [ ] Ownable (set to DebtDAO multisig, singleton for all loans)
- [ ] All prices must be in USD
- [ ] All oracles assumed to be ChainlinkAggregatorV3 so only oracles supported.
- [ ] If no Chainlink oracle in USD, we will create wrapper contract to pull ETH/token price and convert to USD with chainlink ETH/USD oracle with same interface
- [ ] Should we add metadata to denote oracle type to allow non Chainlink oracles or if oracle is denominated in ETH to handle conversion inside Oracle module instead of separate contract mentioned above
- [ ] `addOracle(address token, address oracle)` - adds an oracle address for token address. Can not replace exisiting oracle if it exists
- [ ] `getLatestAnswer(address token)` - looks up oracle for token fetches token price from it (calls getLatestAnswer if Chainlink AggregatorV3).

**Comment by DHG18** [comment]
Ok so after looking into this here are my INITIAL initial questions:

1) based on [this link](https://docs.chain.link/docs/consuming-data-feeds/) it seems as though aggregatorv3 oracle addresses need to be hard-coded for currency pair. This would make it so that there would be one new oracle contract for every new debt position, yes?
2) To answer your question on metadata, I think it depends on whether or not we will be permitting the use of tokens that aren't covered by Chainlink's oracles. Maybe a discussion for product team? It really simplifies things if we just stick to Chainlink. Can also think of reasons why we would not really want to accept a token as collateral that isn't legit enough to be covered by chainlink (much more volatility / price risk). List of all Chainlink USD pairs is [here](https://data.chain.link/ethereum/mainnet/crypto-usd).
