### ISSUE TITLE
Handle arithmetic 

### ISSUE THREAD

**Issue by James-Sangalli** [debtdao/smart-contracts#25]
Since we will be doing a far amount of calculations I think it is good to think about how this logic should be handled and to keep it as simple as possible.

As you know, I propose using the Decimal library as it is logically easier to understand but it would be good to hear all of your thoughts about this and consider all the types of calculations we will be doing. 

Obviously the major ones will be: cratio calculation, repayments and interest rate payments. 

I think it could be a good idea to take the Decimal library and update it to our version of solidity (this would remove the need for `SafeMath`)

**Comment by kibagateaux** [comment]
At the moment i don't totally see the reason for the Decimal library. Doesn't seem like that much is added by it especially if we dont need SafeMath since we're using Solidity v8. I would be keen to hear how you think it would be valuable to the codebase. 

We could also use it in the spigot for revenue splits which does have some logic to accommodate potential uint overflows ([here](https://github.com/debtdao/smart-contracts/blob/f0f7fda42b44042acfa91c794b2989c8a0db834f/contracts/Spigot.sol#L153) for calculations [here](https://github.com/debtdao/smart-contracts/blob/f0f7fda42b44042acfa91c794b2989c8a0db834f/contracts/Spigot.sol#L120
)) for percentage arithmetic so it could definitely potentially help.
